version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsucmVkYWkuc2l0ZSQ
    container_name: redai_frontend_production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_APP_URL=http://localhost:8080
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsucmVkYWkuc2l0ZSQ
      - CLERK_SECRET_KEY=sk_live_XOBM4dWdsiCF86b4SxGiGMLajYcA2omHPe4Xcn6i9w
      - NEXT_PUBLIC_CLERK_FRONTEND_API=clerk.redai.site
      - CLERK_FRONTEND_API=clerk.redai.site
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - redai-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.optimized
    container_name: redai_backend_production
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DEBUG=false
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_BACKUP_KEY=${AZURE_OPENAI_BACKUP_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - USE_AZURE_AD=${USE_AZURE_AD}
    restart: unless-stopped
    networks:
      - redai-network
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
      - generated_images:/app/generated-images
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  ai-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile.ai-processor.optimized
    container_name: redai_ai_processor_production
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_BACKUP_KEY=${AZURE_OPENAI_BACKUP_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
    restart: unless-stopped
    networks:
      - redai-network
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  postgres:
    image: postgres:15
    container_name: redai_postgres_production
    environment:
      - POSTGRES_DB=redai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - redai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redai_redis_production
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - redai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: redai_nginx_production
    ports:
      - "8080:80"
    volumes:
      - ./docker/configs/nginx-redai-no-ssl.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - redai-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'

  prometheus:
    image: prom/prometheus:latest
    container_name: redai_prometheus_production
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - redai-network

networks:
  redai-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local
  generated_images:
    driver: local
  postgres_data:
    driver: local 