version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfiles/Dockerfile.frontend.dev
    container_name: redai_frontend_local
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      
      # Clerk Authentication
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      
      # Azure OpenAI Configuration (NO OpenAI)
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_ENDPOINT_KEY=${AZURE_ENDPOINT_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-05-01-preview}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-gpt-4.1}
      
      # BFL API for image generation
      - BFL_API_KEY=${BFL_API_KEY}
      
      # Domovenok Configuration
      - DOMOVENOK_NAME=${DOMOVENOK_NAME:-Домовёнок}
      - DOMOVENOK_PERSONALITY=${DOMOVENOK_PERSONALITY:-friendly}
      - DOMOVENOK_SPECIALIZATION=${DOMOVENOK_SPECIALIZATION:-realtor}
      - DOMOVENOK_MAX_TOKENS=${DOMOVENOK_MAX_TOKENS:-1800}
      - DOMOVENOK_TEMPERATURE=${DOMOVENOK_TEMPERATURE:-0.7}
      
      # Development Settings
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - redai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/check-status?url=test", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  redai-network:
    driver: bridge

volumes:
  node_modules:
  next_cache: 